### ISSUE TITLE
Possibility to place PredictionHead on inner layer / multiple layers of BaseModel

### ISSUE THREAD

**Issue by Alex-Zien** [deepset-ai/FARM#140]
To improve predictive accuracy it may be beneficial to not (only) use the top layer of the LM, but instead some inner layer, or even a combination of two or more layers.

In https://arxiv.org/abs/1903.05987, using inner layers has been shown to be beneficial in combination with parameter freezing, but it might also have potential with fine-tuning.

**Comment by tholor** [comment]
If you want to use a LM as a pure feature extractor / embedder, FARM already supports different extraction strategies ("cls_token", "reduce_mean" ...) and different layers in the Inferencer.

There are options in the Inferencer
https://github.com/deepset-ai/FARM/blob/30aa9209c5b8840e5c31378d8dd2bcad1365c752/farm/infer.py#L250

which are then used in `LanguageModel.formatted_preds()`
https://github.com/deepset-ai/FARM/blob/30aa9209c5b8840e5c31378d8dd2bcad1365c752/farm/modeling/language_model.py#L168-L194

-------------------

If you however want to use a similar tactic **during training**, you would need to change  `AdaptiveModel.forward()`
https://github.com/deepset-ai/FARM/blob/30aa9209c5b8840e5c31378d8dd2bcad1365c752/farm/modeling/adaptive_model.py#L201-L205
In order to get to the sequence output (not CLS) from an earlier layer you could so something like this: 
``` 
# Run language model
if self.extraction_layer == -1:
	sequence_output, pooled_output = self.language_model(**kwargs)
else:
	self.language_model.enable_hidden_states_output()
	sequence_output, pooled_output, all_hidden_states = self.language_model(**kwargs)
	sequence_output = all_hidden_states[self.extraction_layer]
	self.language_model.disable_hidden_states_output()

...
```

Happy to see a PR here, if you find time to implement this.
