### ISSUE TITLE
Calculating and using Class Weights

### ISSUE THREAD

**Issue by FlorianRauls** [deepset-ai/FARM#142]
When loading Data into the DataSilo there is the (out commented) possibility to calculate the class weights for each class.
If I see correctly the TextClassificationHead can actually handle these class weights when predicting.

Since these features are already there it would be useful to have the option for class weights usage.

A typical use case would be a classification task with imbalanced data (in which class weights to yield a better result in my experience).

**Comment by tholor** [comment]
Class weights are definitely useful and supported by FARM.

We only went away from calculating them automatically within the DataSilo (due to drawbacks in a multitask setting).
 
Instead you can call `data_silo.calculate_class_weights(task_name="text_classification")` to get your weights and pass them then into your prediction head. 

See also the example in examples/doc_classification: 

https://github.com/deepset-ai/FARM/blob/fb6370ad5d99efa0b9126d72ce87c872234fff45/examples/doc_classification.py#L61-L62

**Comment by FlorianRauls** [comment]
Thank you for your quick and helpful reply.

**Comment by rollator3000** [comment]
Hi :wave:, I'm doing a Multi-Label text-classification  & was wondering, if it is meaningful to initialize the prediction head like this:

`
prediction_head = MultiLabelTextClassificationHead(num_labels = len(label_list), class_weights = data_silo.calculate_class_weights(task_name="text_classification"))
`

Or is there rather something like a special 'task_name' for multi-label classification? I've done some research, but could not find anything useful...

Thanks in advance!
Cheers Frederik
