### ISSUE TITLE
Early stopping instead of a fixed number of epochs

### ISSUE THREAD

**Issue by johann-petrak** [deepset-ai/FARM#160]
It should be possible to use early stopping for training, based on minimum loss or some other min/max dev-set metric. 
This could allow an option to save all min models until training was stopped, so that we can use those for ensembling, if needed.

**Comment by johann-petrak** [comment]
I will try to come up with a PR for an initial version of this.

**Comment by tholor** [comment]
That would be great! I can see the value of this feature, but we are currently flooded with work :) 
Happy to support you along the way though!

**Comment by johann-petrak** [comment]
OK, I am hitting an odd problem: for early stopping, I need to save the current best model whenever it turns out to be best so far, then, instead of doing the evaluation on the test set with the current, last model in memory, I need to instead restore to overall best model first and use that.

I try this the following way:
For saving:
```
model.save(wheretosave)
self.data_silo.processor.save(wheretosave)  # so we can restore to Inferencer as well
```

for restoring:
```
# need to restore to the same device we use for the current last model
model_device_type = next(iter(model.parameters())).device.type
# want to use the load method from the same class as our current last model
# instead of making an assumption of what class this should always be
model = model.__class__.load(wheretosave, model_device_type)
```

The main problem this causes is that when I run:
```
self.evaluator_test.log_results(result, "Test", self.global_step)
```
I get the following exception I do not understand at all:
```
Traceback (most recent call last):
  File "examples/doc_classification.py", line 92, in <module>
    model = trainer.train(model)
  File "/home/johann/nlp/GIT/FARM-mine/farm/train.py", line 282, in train
    result = self.evaluator_test.eval(model)
  File "/home/johann/nlp/GIT/FARM-mine/farm/eval.py", line 72, in eval
    losses_per_head = model.logits_to_loss_per_head(logits=logits, **batch)
  File "/home/johann/nlp/GIT/FARM-mine/farm/modeling/adaptive_model.py", line 116, in logits_to_loss_per_head
    all_losses.append(head.logits_to_loss(logits=logits_for_one_head, **kwargs))
  File "/home/johann/nlp/GIT/FARM-mine/farm/modeling/prediction_head.py", line 257, in logits_to_loss
    label_ids = kwargs.get(self.label_tensor_name)
  File "/home/conda/anaconda3/envs/femdwell/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'TextClassificationHead' object has no attribute 'label_tensor_name'
```

The other, minor problem is that the logger complains:
```
WARNING - farm.modeling.adaptive_model -   ML logging didn't work: INVALID_PARAMETER_VALUE: Changing param value is not allowed. Param with key='lm_name' was already logged with value='bert-base-german-cased' for run ID='86b07e7c58814ccd87419ed7d25c2403. Attempted logging new value 'debug-save-model'.
```
The problem here seems to be that the name is set automatically when loading and that logging of the parameters is done immediately without a chance to restore the name first?

So I guess maybe I am restoring the model in the wrong way?

**Comment by tholor** [comment]
Ok, it seems that your `PredictionHead` is not properly linked to the `Processor` after loading. 
Can you please try to add 
`model.connect_heads_with_processor(self.data_silo.processor.tasks, require_labels=True)` 
between model loading and starting your eval?

**Background:**
FARM supports multitask learning (e.g. using 3 different TextClassificationHeads). In that case the processor also needs to produce 3 different types of labels. In order to link each head to the right labels we have the concept of "tasks".  
Each processor starts with a "default task". You can add more of them via: `processor.add_task(name="my_new_task", label_list=["some category", "another"], metric="acc", label_column_name="column_name_in_tsv")`

On the other side each head is initialized with a default task_name. You can use a different name via: 
`custom_head = TextClassificationHead(layer_dims=[768, 3], task_name="my_new_task")
`

Now, to connect both sides, we can call `model.connect_heads_with_processor(self.data_silo.processor.tasks, require_labels=True)`
as done in the [Trainer](https://github.com/deepset-ai/FARM/blob/00e732a5d3032c954375387528333e143f7d0b3f/farm/train.py#L129) and the [Inferencer](https://github.com/deepset-ai/FARM/blob/00e732a5d3032c954375387528333e143f7d0b3f/farm/infer.py#L88).

We found in multiple projects that such multitask learning can boost your performance. However, the implementation is probably one of the most trickiest parts in FARM and we are still looking for options to simplify this.

Let me know, if that helps to solve the issue. If it doesn't, we can dig deeper together...

**Comment by tholor** [comment]
Regarding your second issue with MLflow logging: 
This really seems a minor thing. A simple solution could be adding a boolean flag "logging" to `AdaptiveModel()` and `AdaptiveModel.load()` to avoid logging the params in your case.

**Comment by johann-petrak** [comment]
Thanks, that was exactly what I needed to make it work!
