### ISSUE TITLE
Issue with loading GermEval Dataset in Tutorial

### ISSUE THREAD

**Issue by benjamin9000** [deepset-ai/FARM#162]
**Question**
Hi,
while using the tutorial I get an error message when execeuting 
data_silo = DataSilo(
    processor=processor,
    batch_size=BATCH_SIZE)
**KeyError: "None of [Index(['text', 'coarse_label'], dtype='object')] are in the [columns]"**
I downloaded the data from https://github.com/uds-lsv/GermEval-2018-Data. The corresponding data are .txt files although the DataSilo requires .tsv-files. I converted the .txt-files to .tsv-files and received the error message above. So, how can I get the original data as .tsv (train.tsv and test.tsv)?
Many thanks in advance!

**Additional context**
Add any other context or screenshots about the question (optional).

**Comment by tholor** [comment]
Hi @benjamin9000 ,

Which tutorial are you exactly doing? Tutorial 1 via the jupyter notebook?

The dataset should be downloaded automatically by FARM. Just make sure that there is no existing folder data/germeval18 on your system.

**Comment by benjamin9000** [comment]
Thanks for the quick response!
Yes, I'm doing Tutorial 1via  jupyter notebook.

When adjusting the working directory such that it is the root of FARM ("...\FARM") and then execeuting the DataSilo()-command I get the error 
**File b'data/germeval18\\train.tsv' does not exist: b'data/germeval18\\train.tsv'**
As I didn't find the file train.tsv or the folder "data/" in the repository I tried to download it manually which led to the problems explained in my first post.
So, where does FARM save the dataset?

**Comment by tholor** [comment]
I tried to reproduce the issue on a linux machine, but everything seems to work smoothly there. 

Can you please give some details about your environment: Are you using windows? Does your machine have straight internet access without a proxy? Please also check and post the printout of the notebook cell where the DataSilo gets initialized. It should look something like this and contains some info if the download succeeded and where the dataset got stored:
```I1125 09:00:57.794161 140656609785664 data_silo.py:127] 
Loading data into the data silo ... 
              ______
               |o  |   !
   __          |:`_|---'-.
  |__|______.-/ _ \-----.|       
 (o)(o)------'\ _ /     ( )      
 
I1125 09:00:57.796893 140656609785664 data_silo.py:136] Loading train set from: data/germeval18/train.tsv 
I1125 09:00:57.798634 140656609785664 utils.py:37]  Couldn't find data/germeval18/train.tsv locally. Trying to download ...
I1125 09:00:57.801323 140656609785664 utils.py:138] downloading and extracting file germeval18 to dir /home/mp/deepset/dev/FARM/data
100%|██████████| 525101/525101 [00:00<00:00, 5377703.83B/s]
``` 

In order to get started with the tutorial, you could also download the dataset manually from here and extract it afterward: https://s3.eu-central-1.amazonaws.com/deepset.ai-farm-downstream/germeval18.tar.gz

However, I would appreciate to understand & fix the root cause since other users might encounter similar problems. 

> data/germeval18\train.tsv

The two different backslashes seem suspicious to me. Might be an OS related issue.

**Comment by benjamin9000** [comment]
Yes, I'm using windows and my machine has a straight internet access without a proxy.

The different backslashes are strange. However, the main problem was that there was no folder "data". When downloading the dataset manually and extracting in a data folder at the correct place, the tutorial works fine. So, thanks for the link to the dataset.

**Comment by tanaysoni** [comment]
Hi @benjamin9000, #172 added support for Windows OS in FARM! This should fix the path related issues.
