### ISSUE TITLE
Add XLNet

### ISSUE THREAD

**Issue by tholor** [deepset-ai/FARM#17]
Let's add XLNet as a second language model to the farm. Should be a good first alternative to BERT in many cases.

**Comment by Seb0** [comment]
What do you think about ULMFiT as an alternative for smaller datasets?

**Comment by Timoeller** [comment]
We would be more than delighted if you implement ULMFit for FARM and will support you wherever we can. We believe only a variety of different Representation Models will create a healthy farm : ) or even improve performance when ensembled.

Currently we are implementing the other more recent Language Models and are unsure about ULMFit since the performance seems to be minor compared to BERT and XLNet. For details see [here](https://forums.fast.ai/t/language-model-zoo-gorilla/14623). Also ULMFit is LSTM based, so rather slow in relation to the number of paramteres trained. The QRNN implementation (instead of an LSTM) seems to be faster, but still significantly slower than attention based methods.

You mention ULMfit as an alternative for smaller datasets. 
BERT also seems to be working on smaller datasets. You could easily test how well BERT performs with FARM by setting the "dev_size" parameter in one of the Germeval 2018 configs (in folder experiments/text_classification) to be a list of values, e.g. [0.5,0.7,0.9,0.95]. 
That way you will create small training sets which are evaluated on remaining large development sets. FARM automativally iterates over these values and logs results to our public [MLflow server](https://public-mlflow.deepset.ai/#/).
Use the script run_all_experiments.py and comment out all other configs than the one you modified. If you find a good comparisons where ULMfit converges significantly faster with less training data we might push ULMfit integration internally.
Happy Farming : )

**Comment by tholor** [comment]
Solved wtih #125
