### ISSUE TITLE
How to process the data format for multi-label classification? 

### ISSUE THREAD

**Issue by JiangYanting** [deepset-ai/FARM#189]
**Question**
How to process the data format for multi-label classification? 

**Additional context**
Hello! I’m trying to run the  "**doc_classification_multilabel.py**" in FARM/examples/    using the **toxic comments dataset** in Kaggle. The original data format is as shown below:

id | comment_text | toxic | severe_toxic | obscene | threat | insult | identity_hate
-- | -- | -- | -- | -- | -- | -- | --
0000997932d777bf | Explanation     Why the edits made under my username Hardcore Metallica Fan were reverted?   They weren't vandalisms, just closure on some GAs after I voted at New York   Dolls FAC. And please don't remove the template from the talk page since I'm   retired now.89.205.38.27 | 0 | 0 | 0 | 0 | 0 | 0
000103f0d9cfb60f | D'aww! He matches this background colour I'm seemingly stuck with.   Thanks.  (talk) 21:51, January 11, 2016   (UTC) | 0 | 0 | 0 | 0 | 0 | 0
000113f07ec002fd | Hey man, I'm really not trying to edit war. It's just that this guy is   constantly removing relevant information and talking to me through edits   instead of my talk page. He seems to care more about the formatting than the   actual info. | 0 | 0 | 0 | 0 | 0 | 0
0001b41b1c6bb37e | "     More     I can't make any real suggestions on improvement - I wondered if the   section statistics should be later on, or a subsection of ""types   of accidents""  -I think the   references may need tidying so that they are all in the exact same format ie   date format etc. I can do that later on, if no-one else does first - if you   have any preferences for formatting style on references or want to do it   yourself please let me know.          There appears to be a backlog on articles for review so I guess there may   be a delay until a reviewer turns up. It's listed in the relevant form eg   Wikipedia:Good_article_nominations#Transport    " | 0 | 0 | 0 | 0 | 0 | 0
0001d958c54c6e35 | You, sir, are my hero. Any chance you remember what page that's on? | 0 | 0 | 0 | 0 | 0 | 0
00025465d4725e87 | "          Congratulations from me as well, use the tools well.  talk " | 0 | 0 | 0 | 0 | 0 | 0
0002bcb3da6cb337 | COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK | 1 | 1 | 1 | 0 | 1 | 0
00031b1e95af7921 | Your vandalism to the Matt Shirvington article has been reverted.  Please don't do it again, or you will be   banned. | 0 | 0 | 0 | 0 | 0 | 0

**So, How Should I process this data file to adapt to the doc_classification_multilabel.py for multi-label doc classification ?** (BTW : The tutorial in this repository seems to only have the guide about single-label classification.)

**Comment by tholor** [comment]
Hey @JiangYanting , 

The data should have the following format:

text | label 
-- | --
Explanation Why the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27 | |
COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK | toxic, severe_toxic, obscene, insult |
... | ...

The standard delimiter is "\t", but you can easily change to other via the delimiter arg of the `TextClassificationProcessor`.

You can find the toxic comments dataset in this format [here](https://s3.eu-central-1.amazonaws.com/deepset.ai-farm-downstream/toxic-comments.tar.gz), but it should also be downloaded automatically when you run `examples/doc_classification_multilabel.py`
Let me know in case you have trouble with that.

**Comment by JiangYanting** [comment]
@tholor thank you very much! I'd have a try~
