### ISSUE TITLE
unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by aiwalter** [deepset-ai/FARM#199]
**Describe the bug**
Error occurs when runnin e.g. the "test_doc_classification_distilbert.py"

**Error message**
```
TypeError: initialize_optimizer() got an unexpected keyword argument 'device'
**Expected behavior**
A clear and concise description of what you expected to happen.
```

**Additional context**
Error comes only when installing via pip. Installation via GitHub was working fine, so it seems the error was already fixed, however not commited to PyPI?

**To Reproduce**
Execute the "test_doc_classification_distilbert.py" file with `language_model = Roberta.load(lang_model, language = "multilingual")`

**System:**
 - 4.15.0-1066-azure (Ubuntu 16.04 LTS (Xenial Xerus))
 - GPU/CPU:
 - FARM version: 0.3.2

**Comment by tholor** [comment]
Hey @aiwalter, 

You are totally right. This is due to a version mismatch between the example and the latest FARM version on pypi (2.3.0).

We changed the signature of `initialize_optimizer()` in #133, but didn't do a release since then. 
We will probably do one later this week, when we are done with a few other big features (conversion to transformers, caching + checkpointing during training ...)

Until then you have two options: 
a) FARM pypi version + "old" examples from tag 0.3.2 (https://github.com/deepset-ai/FARM/tree/0.3.2)
b) FARM master version + current examples

Hope that helps :)

**Comment by aiwalter** [comment]
Hi @tholor , 
thx for fast feedback. I just wanted to document this error, as others might also face it :)
Please close this issue as soon as you have released the new version at PyPI.
