### ISSUE TITLE
MLFlowLogger: "Connection aborted." - RemoteDisconnected Error

### ISSUE THREAD

**Issue by JiangYanting** [deepset-ai/FARM#217]
**Describe the bug**
I try to do multi-label classification with "doc_classification_multilabel.py". It worked at first. However when it came to `"Train epoch 1/1:  65%|██████▍   | 17251/26668 [10:19:41<4:04:28,  1.56s/it]"`, it stopped and report:

```
  File "/home/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
......
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

  I have checked that the Internet connection was ok. So I was confused why this error occured ?
  

**Error message**
Error that was thrown (if available)

**Expected behavior**

**Additional context**
Add any other context about the problem here, like type of downstream task, part of  etc.. 

**To Reproduce**
Steps to reproduce the behavior

**System:**
 - OS: 
 - GPU/CPU:
 - FARM version:

**Comment by tholor** [comment]
Hey @JiangYanting, 

Are you using our public mlflow server for logging (i.e. `ml_logger = MLFlowLogger(tracking_uri="https://public-mlflow.deepset.ai/")
` in doc_classification_multilabel.py)? 

I would assume that your connection to that server was not available when the model tried to logg the train_loss at step 17251. 

I see two solutions:
- short term: you can log locally by setting `ml_logger = MLFlowLogger(tracking_uri="")`
- mid term: implementing a fix in FARM, so that we raise only a warning, if the logging doesn't succeed, but let the training continue. Let me know if you are interested in adding a PR for this. Otherwise, we can take care. It would be basically a try / catch block here: https://github.com/deepset-ai/FARM/blob/master/farm/utils.py#L126

**Comment by JiangYanting** [comment]
@tholor By setting `ml_logger = MLFlowLogger(tracking_uri="")` , it works. Thank you very much ! ^_^
