### ISSUE TITLE
Update Examples

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#227]
The examples are really useful but are no longer up-to-date.
https://github.com/deepset-ai/FARM/blob/master/examples/doc_regression.py

* For example, the model is passed to the trainer.train(model) and not in the constructor anymore
* It seems distilBERT uses standard BERT tokenizer so using lang_model for distilBERT to load both the tokenizer and the model itself won't work. But solving this was straight forward, by using seperate names.
* Maybe specifying a variable for layer_dims like you did in the tutorial would help newbies like me. I used [768, 1]
* At last, the data path requires the data to be found in a data/ folder and the actual training file to be called train.tsv. If it is mandatory, a little comment on that might help

Keep up the awesome work :))

**Comment by zolekode** [comment]
My Bad concerning the training file name. I now see we can pass it as an argument.

**Comment by tholor** [comment]
Hey @zolekode ,

Thanks for reporting! It's sometimes tricky to keep all examples up-to-date.

> For example, the model is passed to the trainer.train(model) and not in the constructor anymore

 Yep, totally right.

> It seems distilBERT uses standard BERT tokenizer so using lang_model for distilBERT to load both the tokenizer and the model itself won't work. But solving this was straight forward, by using seperate names.

Using the `lang_model` for loading the tokenizer should actually work. Is it possible that you use an older version of transformers? Since their last release is quite a while ago, I would recommend installing from their latest master branch and not from pypi. If the problem still persists, please let me know.

Would you be up for creating a PR with the updated example? We would really like you to become a FARMer :)

**Comment by zolekode** [comment]
Yes it is a version problem. Installing transformers and FARM directly from github solved the issue. Yes, i would gladly farm :)) 👍
