### ISSUE TITLE
How to add Custom Layers

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#231]
How can i specify custom layers ?
For example, instead of [768, 1] for regression, I would like to have [768, X]=>[X, 1] for example

**Comment by brandenchan** [comment]
Hey, is it that you want to specify a deeper feed-forward layer as the prediction head?

If so you can initialize an n-layered prediction head by setting the layer_dims argument. It should be a list specifying the input and output dimensions of each layer. So for a 2 layer feed forward network for regression you might have something like RegressionHead(layer_dims=[768, X, 1]).

I am curious to see whether this improves your model though it is not something that we usually experiment with since the top layers of the language model are also trainable and should already have enough capacity to learn the domain specific task.

**Comment by zolekode** [comment]
Ah thanks. Yes, I just tried it and it didn't improve the performance.
