### ISSUE TITLE
Inference Verbosity, how to disable logger / logging / print output?

### ISSUE THREAD

**Issue by zolekode** [deepset-ai/FARM#247]
@Timoeller 
Please how can turn off the prints at inference time ?
```Inferencer.load(model_dir, task_type="text_classification", gpu=True)``` 
Furthermore, is it me or inference is a little slower ?

**Comment by Timoeller** [comment]
True, especially for inference there can be quite a lot of output.

To be nit picky: FARM isn't printing, it is logging.
[Here](https://stackoverflow.com/questions/2266646/how-to-i-disable-and-re-enable-console-logging-in-python) you can find more info on how to disable logging in various ways. 
For your use case turning off all logging like
`import logging`
`logging.disable(logging.CRITICAL)`
should work.
I also edited the issue title, so other people can find it better. 

About **inference time**, try increasing the batch size like:
`Inferencer.load(model_dir, task_type="text_classification", gpu=True, batch_size=200)`
Inference mode doesnt use as much GPU memory as training since you are not storing so many states. It would be nice if you could benchmark the inference time for your use case for some batch sizes and report them here. Thanks!

**Comment by zolekode** [comment]
Yes my bad, i meant logging. Ah thank you very much for the hint 🎸 🥇. Yes, regarding inference, i am not quite sure because i just realised i only have one CPU locally. I will try again later with a better pc. If i notice any difference in performance i will benchmark and post it on another thread.
