### ISSUE TITLE
Example of file format for NER

### ISSUE THREAD

**Issue by andra-pumnea** [deepset-ai/FARM#287]
Hey! I think it would be useful to have a more detailed explanation about:

1. what the dataset should look like for performing NER, similar to the [fine-tuning example](https://github.com/deepset-ai/FARM/blob/97b0211a37ea7c7d64b4602f0e21b65428b2bd76/test/samples/lm_finetuning/test-sample.txt#L1). The [NER sample](https://github.com/deepset-ai/FARM/blob/97b0211a37ea7c7d64b4602f0e21b65428b2bd76/test/samples/ner/train-sample.txt#L1) is great and I think it could be further improved to include an explanation about what input is expected: format of the dataset, separating sentences with newlines etc. 

2. what the [start_token, end_token] mean in label_list for NER.  Documentation on why we need label_list=['[PAD]', 'X', label1, label2, ...]. 

I could also help with the first one, based on my learnings so far :)

**Comment by Timoeller** [comment]
That is a great idea, since especially for NER we saw quite some confusion about the right data format.
Would you like to create a short doc and place it under docs/data/ner.rst

**Comment by andra-pumnea** [comment]
yeah, I will do it this week 😄

**Comment by andra-pumnea** [comment]
The other samples and examples of what the input needs to look like for different tasks are under FARM/test/samples/ . Maybe it's a good idea to have them all in in the new docs/data/ ? (there seems to be no docs/data/ yet)

**Comment by Timoeller** [comment]
Good question. Handling this correctly will be difficult.

Problem: We need the samples in test/samples for testing, so I would leave them there. 

Solution: You could copy or link them (maybe in different format) in the docs section?

Any suggestions how we could handle changes? E.g. if we update the format in one place all other places should be adjusted, too. 
My thoughts: I would like to leave the data examples in the test folder, since these have to match exactly the needed format. If they do not match we get email notifications of failing tests. What are automated processes to select some or even change the test samples for better visualizations in our documentation?

**Comment by andra-pumnea** [comment]
I understand now why the test/samples are there. I can create a document with the formats for all the tasks in test/samples/  in docs/data/ , but I don't think I understood your thoughts about how to update both files automatically.

**Comment by Timoeller** [comment]
Good that you asked. I think it is a simple concept but I phrased it in a twisted way : )

I think it is important that files in FARM/test/samples and FARM/docs/data are always matching. If one file is updated, the other should be updated in an automatic manner, too.
We can assure this by either 
1. Referencing data in docs/data to point to test/samples  
or
2. Creating a script that takes test/samples and automatically converts them to a format useful for our docs

Do you think that makes sense and you would like to implement it? We are also very open to alternatives, maybe there is another solution that fits our needs better? Happy to discuss them.

**Comment by andra-pumnea** [comment]
yes, I'll work on it :)
