### ISSUE TITLE
Not able do install 

### ISSUE THREAD

**Issue by VikasRajashekar** [deepset-ai/FARM#344]
When I tried to do the installation of both kinds mentioned in read me I get the following error.
ERROR: Command errored out with exit status 1:
```
     command: /home/vikas/anaconda3/envs/farm2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ioqruh2n/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ioqruh2n/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ioqruh2n/onnx/pip-egg-info
         cwd: /tmp/pip-install-ioqruh2n/onnx/
    Complete output (6 lines):
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ioqruh2n/onnx/setup.py", line 72, in <module>
        assert CMAKE, 'Could not find "cmake" executable!'
    AssertionError: Could not find "cmake" executable!
```
How to resolve it?

**Comment by veljkoselakovic** [comment]
You should install cmake and add it to PATH. I've experienced the same problem but solved it that way.  I still can't actually install it, since I get a massive error, but that is probably a question for the people working on onnx, since it looks like that's the perpetrator. I'm also having trouble because I can't actually install FARM on pytorch 1.5.0 since the dependencies specify torch==1.4.0. I tried changing the requirements.txt manually but I got the aforementioned issue.

**Comment by tanaysoni** [comment]
Hi @VikasRajashekar, the error seems like in the installation of `onnxruntime`. With #347, the dependency is now optional.

Can you try installing again after doing a `git pull` to get latest changes on the FARM master branch and installing by executing `pip install -e .`?
