### ISSUE TITLE
More convenient way of output test predictions

### ISSUE THREAD

**Issue by stefan-it** [deepset-ai/FARM#353]
Hi,

it would be an awesome feature, if the predictions made on the test set could be written to an output file.

E.g. the Hugging Face Transformers fine-tuning code for NER just outputs a file (`test_predictions.txt`) with Token and the predicted label (per line, same format as original test set).

This would really help evaluation with external scripts, e.g. the official CoNLL evaluation script could be used (with minor pre-processing steps).

I think this can be done with the `Inferencer` class and some lines of code, but having an easy solulution would be great for users: e.g. by just specifying an output file were all predictions are written to (`predictions_file` key name in configuration).

What do you think 🤔

**Comment by Timoeller** [comment]
Hey @stefan-it that is a great idea. We have already a function that does something similar for QA predictions. If you want please create an optional attribute in the Inferencer.

One word of caution though, we are currently working on passing single datapoint IDs through the model, since multiprocessing might mess up the order of returned results. This is something that is coming up a lot lately and we will try to fix that, soon. For now you could disable multiprocessing (that fixes the order) when the predictions_file arg is set and display a warning.

**Comment by Timoeller** [comment]
Small update concerning ordering of inferencer results. We tested it and the order is assured, even with multiprocessing (details see  [here](https://github.com/deepset-ai/FARM/issues/332#issuecomment-627338563)). So you could just add the flag and write predictions to file.
