### ISSUE TITLE
Task type "embedding"

### ISSUE THREAD

**Issue by lubok-dot** [deepset-ai/FARM#372]
**Describe the bug**
If inferencer is loaded with task_type="embedding" and lang_model='bert-base-german-cased' it complains about not finding the processor_config.json file.

**Error message**
FileNotFoundError: [Errno 2] No such file or directory: 'bert-base-german-cased\\processor_config.json'

**Expected behavior**
processor_config.json should be loaded for initializing the tokenizer 

**Additional context**
The error message rises in line 577 of processor.py

**To Reproduce**
lang_model = 'bert-base-german-cased'

model = Inferencer.load(lang_model, task_type="embeddings", gpu=False, batch_size=32, extraction_strategy="reduce_mean", extraction_layer=-1, num_processes=0)

**System:**
 - OS: Windows
 - GPU/CPU: CPU
 - FARM version: 0.4.3

**Comment by Timoeller** [comment]
Hey @lubok-dot I cannot reproduce the error on my end - I use Ubuntu instead of Windows. Though I suspect your issue should not be related to OS. 

Could it be that you have a local folder named "bert-base-german-cased" in your working directory? I am asking since line 577 of processor.py should only be called in case the "lang_model" points to a local directory. Check the if else condition in the Inferencer.load function [here](https://github.com/deepset-ai/FARM/blob/master/farm/infer.py#L189).
Could you delete this folder or try other bert models like "dbmdz/bert-base-german-cased"?

**Comment by lubok-dot** [comment]
Thanks a lot for the quick response -- indeed, I had a local download of 'bert-base-german-cased' model on my machine because I thougt one could also load the model from this download instead of the version in the Cloud. Using the Cloud version works! Thank you.

**Comment by Timoeller** [comment]
Nice!
Yes the loading functionality is a bit complex because we cover many different cases - but it can of course be improved. 
For now a local model is always handled as a FARM specific model, we will make this more flexible in the future.

I also changed the title of the issue, so other people can find answers to similar issues.
