### ISSUE TITLE
Regression label float to int conversion bug

### ISSUE THREAD

**Issue by rohanag** [deepset-ai/FARM#395]
**Describe the bug**
https://github.com/deepset-ai/FARM/blob/master/farm/data_handler/dataset.py#L22 causes float labels in RegressionProcessor to be converted to longs.

**Error message**
Silent error, all my regression labels are being converted to longs.

**Expected behavior**
Regression labels should be retained as floats.

**Additional context**
None

**System:**
 - OS: Ubuntu 16.04.5 LTS
 - GPU/CPU: Both
 - FARM version: upto commit https://github.com/deepset-ai/FARM/commit/b8c52992bfd8a68bf6867201b2ef48d5d151a4fe
 - torch version: 1.4.0

**Comment by Timoeller** [comment]
Hey @rohanag thanks for reporting.
I can reproduce the bug - very strange that torch can cast a float to long quietly...

One possible solution might be to remove the try catch block completely, since we updated to torch 1.5.0 casting is done dependent on numpy input type. Though this change will affect all our tasks that I do not see this change happen quickly.

Could you try out removing the try catch block and test if it works for your regression use case? That would be highly appreciated.

**Comment by rohanag** [comment]
Thanks Tim, will try it out, give me a few days though :)

**Comment by rohanag** [comment]
@Timoeller Sorry for the super long wait. I just tried with the latest version of pytorch 1.5.1, transformers 3.0.2, and FARM v0.4.5 (latest commit as of July 9 2020) and am still getting the same bug.

**Comment by rohanag** [comment]
But you're right, removing the try catch block and dtype argument works in fixing the bug

**Comment by Timoeller** [comment]
Ok thanks for the info. This is a good motivation to try removing the try catch block altogether.
We will need to do quite some testing though, so again, this change will take some time...
