### ISSUE TITLE
How to evaluate using Labels available in dev and not all labels?

### ISSUE THREAD

**Issue by AhmedIdr** [deepset-ai/FARM#399]
**Question**
Hey, im wondering if there is way to change the evaluation so that it only uses the labels that are found in the dev set. In my case there is multiple labels that are in the training set but not in the dev.
**Additional context**
Here is screenshot from the classification report
<img width="304" alt="farm" src="https://user-images.githubusercontent.com/31652778/83749840-46029d80-a65c-11ea-9aac-232fe6866fba.png">

Thank you in advance

**Comment by Timoeller** [comment]
Hey @AhmedIdr, changing the labels that get into the classification report is currently not possible.

Do you want to get the macro average and exclude missing labels in dev?

How about you exclude datapoints with these labels from your training set altogether? Because if you do not care about them during eval you also waste precious gradient flow on these labels during training ;)

**Comment by AhmedIdr** [comment]
Hey @Timoeller, thank you for your feedback I will try excluding the datapoints with the missing labels, I didn't think about that hahah. I will close the issue now.
