### ISSUE TITLE
How to get Inferencer output for token_classification & sequence_classification heads at the same time?

### ISSUE THREAD

**Issue by FTuma** [deepset-ai/FARM#408]
**Question**
I'm currently in the process of building an custom processor with a sequence_classification & a token_classification head. After some small adjustments to the FARM codebase and the creation of a new type of processor, I was able to sucessfully train and evaluate my model on the eval & test data but I'm stuck predicting on new inputs... 

My task at hand is about Joint Intent Classification & Slot Filling, e.g. basically text classification + NER but could probably easily extended to any other task involving joint token & sequence classification and I would be open to provide a PR once it is working properly  (at the very least for the more specific Joint Intent Classification & Slot Filling Task).

I would like to know what's the easiest/best way to get the inference output result for a custom task consisting of 1 token_classification & 1 sequence_classification head. 
Currently I'm running into an KeyError because it's using the else clause used for the Natural Questions in formatted_preds of the trained model.

**Additional context**

![FARM_error_screenshot](https://user-images.githubusercontent.com/35799253/84661004-fb193d80-af19-11ea-9c4f-210978118ca0.PNG)

**Comment by brandenchan** [comment]
Hi, yes that's right, currently the inferencer's multi-head functionality is tailored to Natural Questions. So let me give you a bit of an overview of this code so that we can find you a solution.

Each prediction head has a formatted_preds() which needs either logits or preds_p as input in order to function. In practice, we pass in both a logits and preds_p [here](https://github.com/deepset-ai/FARM/blob/c2118e32121041ed0b9f6a87d65b2cab33858821/farm/modeling/adaptive_model.py#L122) but one of them can be None. In the Natural Questions case, [the logits are Nones](https://github.com/deepset-ai/FARM/blob/c2118e32121041ed0b9f6a87d65b2cab33858821/farm/modeling/adaptive_model.py#L114).

To get this to work for the non-Natural Questions case, we would have to change adaptive_model.py lines 112-114 to something like this:

```
preds = kwargs.get("preds_p", None)
if preds:
    preds_for_heads = stack(preds)
    logits_for_heads = [None] * n_heads
else:
    preds_for_heads = [None] * n_heads
    logits_for_heads = logits
```

This is just from the top of my head and I haven't managed to test it yet but if you'd like to open a PR already, I'm sure I could help you debug more directly! In any case, it's cool to see you've gotten this far into the code! Let me know if this solution helps or not

**Comment by rdemorais** [comment]
Hi guys, I'm looking after the same. Is there any development on this?

**Comment by johann-petrak** [comment]
I have run into the same issue trying to get a very simply two head MTL processing running where both heads are simply text classification heads. 
An attempt to run inference gets an exception complaining about the key "preds"  (not "preds_p") not being found in kwargs. 
Apparently the following keys ARE in kwargs: `['samples', 'tokenizer', 'return_class_probs', 'input_ids', 'padding_mask', 'segment_ids']`

When I change the code to instead do:
```
            preds_for_heads = [None] * n_heads    
            logits_for_heads = logits             
            preds_final = [list() for _ in range(n_heads)]
```

The next error occurs with not finding the key "baskets"  in kwargs which apparently is used to get the samples, but there is already a key "samples"  in kwargs anyways!

Is there some knowledge about which kwargs are passed when here and what the plan is to do this in different situations? 

Is this known to not work or am I using it wrongly -- and if it does not work, are there any workaround for doing inference on a trained multihead model? 

BTW, how is inference supposed to happen during training when regular evaluations are performed? 

As I mentioned in another issue, I am back trying to do some MTL with FARM, but I am unsure to even understand what is supposed to work and what not.

**Comment by johann-petrak** [comment]
OK, one step closer: part of the problem seems to be in the Inferences, line https://github.com/deepset-ai/FARM/blob/bec0a9aeecd696d94e42c72bef6e8b6788a381e0/farm/infer.py#L583

There , only the first element of the returned logits array is assigned to `logits` and then when passing to "formatted_preds" that element gets packed into a list again. 
When I instead get the whole logits list for the batch and pass it on directly like that:
```
            with torch.no_grad():
                logits = self.model.forward(**batch)     # use all elements
                preds = self.model.formatted_preds(
                    logits=logits,     # do not re-pack in lsit
                    samples=batch_samples,
                    tokenizer=self.processor.tokenizer,
                    return_class_probs=self.return_class_probs,
                    **batch)
                preds_all += preds
```
and I also change the `AdaptiveModel.formatted_preds` method as above, it seems to almost work for me: I am getting two predictions (one for each head, I think), but both prediction dicts have an entry `'task': 'text_classification'` when these should really be the proper task names I assigned.

**Comment by johann-petrak** [comment]
Could we maybe re-open this or have a new issue to discuss how to progress on this? 

I may be able to get this to work for my specific heads, but since I do not understand the whole picture/design what I am doing here may break other configurations. 

How does one properly run unit tests after making changes - is this documented somewhere? More generally are there any developer docs? 

For example I tried to run "python setup.py test"  I immediately got a deprecation warning and an exception ModuleNotFoundError: No module named 'transformers.modeling_bert'

**Comment by Timoeller** [comment]
Yes we can reopen this issue. We would be super happy about contributions here but since it is not a high priority for us it will be difficult to implement something ourselves. At the same time the `AdaptiveModel.formatted_preds` is rather complex and we would need to make sure the implementation does not become to complex while being able to do MTL.
By the way, the multi head Inference implementation for Natural Question is currently not supported in FARM, see https://github.com/deepset-ai/FARM/issues/739

**Comment by johann-petrak** [comment]
Added a commit to the PR which should bring this a step closer. At least multiple text classification head inference works now.
