### ISSUE TITLE
Training from Scratch of loaded checkpoint fails in O2 AMP mode

### ISSUE THREAD

**Issue by tstadel** [deepset-ai/FARM#425]
**Describe the bug**
When running the train_from_scratch.py script from examples and there is already a checkpoint, training crashes with the following exception:

**Error message**
```
Traceback (most recent call last):
  File "train_from_scratch.py", line 159, in <module>
    train_from_scratch()
  File "train_from_scratch.py", line 150, in train_from_scratch
    trainer.train()
  File "/home/thomas/git/FARM/farm/train.py", line 293, in train
    loss = self.backward_propagate(per_sample_loss, step)
  File "/home/thomas/git/FARM/farm/train.py", line 400, in backward_propagate
    self.optimizer.step()
  File "/home/thomas/anaconda3/envs/ml/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/thomas/anaconda3/envs/ml/lib/python3.8/site-packages/apex/amp/_process_optimizer.py", line 359, in new_step
    self._master_params_to_model_params()
  File "/home/thomas/anaconda3/envs/ml/lib/python3.8/site-packages/apex/amp/_process_optimizer.py", line 17, in _master_params_to_model_params
    if len(stash.all_fp16_params) > 0:
AttributeError: 'AmpOptimizerState' object has no attribute 'all_fp16_params'
```

**Expected behavior**
Training can be resumed from checkpoint.

**Additional Context**
other AMP modes work fine

**To Reproduce**
run `train_from_scratch.py` until first checkpoint is created (right after start).
run `train_from_scratch.py` again.

**System:**
 - OS: Ubuntu 18.04
 - GPU/CPU: GPU (V100)
 - FARM version: latest from git
 - pytorch version: 1.5.1
 - CUDA version: 10.2

**Comment by tholor** [comment]
Hey @tstadel , 

Sorry, we somehow missed your issue here. Thanks for reporting this bug. We only use the O1 mode for training via AMP and therefore only tested this one.    

Judging from the error message, it seems that there is an additional attribute of the optimizer for O2 (`all_fp16_params`) that we don't save properly in `Trainer.save()` or restore in `Trainer._load_checkpoint()`. Unfortunately, I currently don't have time to investigate this deeper.

Have you maybe already found the issue by now yourself or would be interested in investigating this further if O2 Mode is important to you?

**Comment by tstadel** [comment]
No prob... 
I just haven't dealt with O2 before and stumbled upon it while executing the train_from_scratch script. As I see it, anything else than O1 is more or less experimental. So there is no special need for O2 from my side. 
In addition, I don't think it makes much sence to invest more time into it, as AMP now gained first class support in pytorch 1.6.

**Comment by tholor** [comment]
Ok got it. I also think that we should rather switch to AMP in pytorch 1.6 than fixing this one now.
