### ISSUE TITLE
Add Electra Specific Classification Head

### ISSUE THREAD

**Issue by PhilipMay** [deepset-ai/FARM#530]
FARM has a genereric classification head: https://github.com/deepset-ai/FARM/blob/d7b5cb61f062436789aa9081a85ade4f56e2db6f/farm/modeling/prediction_head.py#L240

Electra from Transformers seems to have a specific head with a gelu activation: https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_electra.py#L397

Should this also be added in FARM?

**Comment by Timoeller** [comment]
Differences in PredictionHeads is definitely something to watch out for, especially when converting trained models between FARM and transformers.

About gelu I found: https://github.com/deepset-ai/FARM/pull/364

I would not like to add a special Electra Prediction Head, since it seems rather random. Only the interoperability with transformers for doc classification is an issue. What about creating error messages in the conversion functions for these cases as is done for roberta model, e.g. [here](https://github.com/deepset-ai/FARM/blob/master/farm/modeling/adaptive_model.py#L537)?

**Comment by Timoeller** [comment]
Seems inactive - closing this for now.
