### ISSUE TITLE
Unstable libriary

### ISSUE THREAD

**Issue by Kapil-Pathak** [deepset-ai/FARM#592]
Hi,

If I install the library from master,

!pip install git+https://github.com/deepset-ai/haystack.git

I am not able to import FARMReader. More specifically cell doesn't stop execution at all.

from haystack.reader.farm import FARMReader

On the contrary, If I install the library with the following commit, I can import FARMReader but not able to import ElasticsearchRetriever

git commit:
!pip install git+git://github.com/deepset-ai/haystack.git@ef9e4f4467a2e265bad72b048a1a3186e40969b1

Code to import ElasticsearchRetriever:

from haystack.retriever.sparse import ElasticsearchRetriever

error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-23-ab0e4f41b185> in <module>
---->from haystack.retriever.sparse import ElasticsearchRetriever

ModuleNotFoundError: No module named 'haystack.retriever.sparse'

Please solve the bug

**Comment by Timoeller** [comment]
Hey @Kapil-Pathak both FARM and haystack are under quite some development, so haystack depends on the FARM version specified in haystacks requirements.txt

Since the error is on haystack side, could you post the error as an issue there please? Then other people running into this problem can find the solution as well.

**Comment by tholor** [comment]
Continued in https://github.com/deepset-ai/haystack/issues/499
