### ISSUE TITLE
Is there any multi-task Learning example available?

### ISSUE THREAD

**Issue by imdiptanu** [deepset-ai/FARM#724]
**Question**
Hello, I am looking for an example of multi-task Learning using the framework. Is there any such example available? To be specific, the problem I am trying to solve is similar to MTL with Text Classification + NER. 

I would really appreciate if anyone could direct me to an example. 

**Additional context**
For now I created a new processor, where I generate all the **features** (_input_ids, padding_mask, segment_ids, initial_mask, task_a_label_ids, task_b_label_ids_). Following the instructions from previous answers [1](https://github.com/deepset-ai/FARM/issues/499), [2](https://github.com/deepset-ai/FARM/issues/139).

> head_a = TextClassificationHead(layer_dims=[768, 3], task_name="task_a")
> head_b = TokenClassificationHead(layer_dims=[768, 2], task_name="task_b")
> 
> model = AdaptiveModel(
>     language_model=language_model,
>     prediction_heads=[head_a, head_b],
>     lm_output_types=["per_sequence", "per_token"],
> )

While training I am getting the error below - 

```
Train epoch 0/0 (Cur. train loss: 0.0000):   0%|          | 0/402 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-bd7ca549ab20> in <module>()
----> 1 model = trainer.train()

2 frames
/usr/local/lib/python3.7/dist-packages/farm/train.py in train(self)
    299                 # Forward & backward pass through model
    300                 logits = self.model.forward(**batch)
--> 301                 per_sample_loss = self.model.logits_to_loss(logits=logits, global_step=self.global_step, **batch)
    302                 loss = self.backward_propagate(per_sample_loss, step)
    303 

/usr/local/lib/python3.7/dist-packages/farm/modeling/adaptive_model.py in logits_to_loss(self, logits, global_step, **kwargs)
    382         # This aggregates the loss per sample across multiple prediction heads
    383         # Default is sum(), but you can configure any fn that takes [Tensor, Tensor ...] and returns [Tensor]
--> 384         loss = self.loss_aggregation_fn(all_losses, global_step=global_step, batch=kwargs)
    385         return loss
    386 

/usr/local/lib/python3.7/dist-packages/farm/modeling/adaptive_model.py in loss_per_head_sum(loss_per_head, global_step, batch)
    201     Output: aggregated loss (tensor)
    202     """
--> 203     return sum(loss_per_head)
    204 
    205 class AdaptiveModel(nn.Module, BaseAdaptiveModel):

RuntimeError: The size of tensor a (32) must match the size of tensor b (988) at non-singleton dimension 0
```

Thank you for the help.

Best,
Diptanu

**Comment by imdiptanu** [comment]
The processor code is here - https://www.codepile.net/pile/1VDvaaBz

**Comment by Timoeller** [comment]
Hey thanks for using FARM for multitask learning.

I see you have created an own processor for it. I am unsure if this custom setting can work within FARM.
It is quite hard to debug this custom code because of a couple of reasons:
The code of MTLProcessor is in the old and complicated style of conversion using `_dict_to_samples` and `_sample_to_features`. Please have a look at the TextClassificationProcessor and dataset_from_dicts method to see how you could implement the Processor in a more simple way.

In any case, please support a fully functioning example script + sample data so we can run the code and replicate the error on our side. That way we might be able to help you.

**Comment by imdiptanu** [comment]
Hi Timo,

Thank you for the prompt reply. The `dataset_from_dicts` method is really a timesaver. I think the available custom processor tutorial is old. However, I wrote a script to replicate the issue on Colab - 

https://colab.research.google.com/drive/1JXNZfcp7Yjibv6DxcublTndIiN6TfNCC?usp=sharing

I hope you can access it. If you can not please let me know. Also, thank you for the help. I appreciate it. If we could work it out, I am willing to write an MTL example, if the team does not mind. 

Best,
Diptanu

**Comment by imdiptanu** [comment]
Hey @Timoeller, Did you get a chance to look into this? Or any suggestions? 

- Diptanu

**Comment by Timoeller** [comment]
Hey @imdiptanu sorry for the delay.

I shortly looked at it, everything seems ok during conversion. Looking at the sample printout "Clear Text" and "Features" it seems the conversion was correct.
My hypothesis is that the label features (document_level_task_label_ids and token_level_task_label_ids) are not parsed to the PredictionHead in the correct way.
Though I did not find time to look into this more deeply. @tholor could you take over here, since you are more deep into MTL in FARM?

**Comment by imdiptanu** [comment]
Thank you for the reply. I am unsure about features not parsed to PredictionHead correctly because I tried to run the two tasks separately, and they ran as expected.

**Comment by tholor** [comment]
Hey @imdiptanu , 

I had a quick look and it seems that all your processing is correct - great job!
The step where things crash is the aggregation of the loss of the two prediction heads. 
The problem here is that you have one token-level and one document-level task. While the document-level task returns a tensor of shape 32 (one per sample in the batch) the token-level loss is (in my test) 893 (one per token in the batch except padding tokens). Calling `torch.sum` on those two tensors of different shape causes the problem:

Luckily there's a simple solution for this in FARM: You can pass a custom `loss_aggregation_fn` to the adaptive model when you initialize it. This function defines how to aggregate the loss from a list of Tensors to a single Tensor. 
It's used here in the code... 
https://github.com/deepset-ai/FARM/blob/719cd81999de491bff9693e8e4a8713f46cdf69e/farm/modeling/adaptive_model.py#L382-L385
and you can just add a snippet like this to your notebook: 
```python
from typing import List
def loss_agg(individual_losses: List[torch.Tensor], global_step=None, batch=None):
    loss = torch.sum(individual_losses[0]) + torch.sum(individual_losses[1])
    return loss

model = AdaptiveModel(
    language_model=language_model,
    prediction_heads=[document_level_task_head, token_level_task_head],
    embeds_dropout_prob=EMBEDS_DROPOUT_PROB,
    lm_output_types=["per_sequence", "per_token"],
    device=device,
    loss_aggregation_fn=loss_agg)
....
```
Hope this helps!

**Comment by imdiptanu** [comment]
Thank you, that fixed the issue. Do you mind if I write an example/tutorial on using FARM for MTL using custom dataset? 

![29-thank-you-meme-1](https://user-images.githubusercontent.com/35115483/109499417-e1496780-7a62-11eb-96ca-9fae490e6d13.png)

**Comment by Timoeller** [comment]
Not at all. We would highly appreciate a MTL example.

If you have data we can also upload it to our s3 so people can work with the example out of the box.
Otherwise a integration of huggingface datasets library (if you can download your example dataset there) would also be an option. Though I think this will need a more comprehensive PR : )

**Comment by imdiptanu** [comment]
I will create a PR and make sure it works out of the box. :)

**Comment by Timoeller** [comment]
Hey @imdiptanu did you had a chance to create a MTL example? There is increasing interest in this, see #742 
Would love to get your contribution into FARM!

**Comment by johann-petrak** [comment]
@imdiptanu would it be possible to make that colab notebook accessible somehow or share the notebook in some other way?

**Comment by imdiptanu** [comment]
Hello @johann-petrak, I have created a new notebook for that, which should be accessible for everyone.  
https://colab.research.google.com/drive/1AGUbcDG_WTaT5OBL1z7KUI0OFVadyYXK?usp=sharing
