### ISSUE TITLE
AdapterFusion with FARM

### ISSUE THREAD

**Issue by agrov** [deepset-ai/FARM#728]
**Question**
Hi, 

Could you please confirm if it is possible to integrate Adapter modules (https://adapterhub.ml/) within FARM's framework?
Currently, I am experimenting with Multi-task learning using FARM and want to compare my results with AdapterFusion. It would be good to know if Adapters can be included within the same architecture.

Thanks!
Anjali

**Comment by Timoeller** [comment]
Adapters seem interesting and also the people from UKPLab have very high engineering standards.
Looking at the docs of adapter-transformers it seems they add code components to the models "adapter-transformers, an extension of Huggingface’s Transformers library that adds adapter components to transformer models". 

So it seems FARM does not have native support for the adapter transformers.
Could you give some more info on these adapter components and how they could be useful.

Also from their github page: "This library can be used as a drop-in replacement for HuggingFace Transformers and regularly synchronizes new upstream changes." I would prefer to not use it as drop in replacement since we would depend on adapter transformer for updates.

**Comment by Timoeller** [comment]
Hey @agrov any progress on the Adapter Modules?

**Comment by agrov** [comment]
Hi @Timoeller, sorry for the delayed response.  

To answer your question on how Adapter modules can be integrated into the FARM architecture:
With the adapter-transformers library we can use their add adapter function to include the adapters in our model. 

from transformers import AdapterType
# Add a new adapter
model.add_adapter("rotten_tomatoes", AdapterType.text_task)
# Add a matching classification head
model.add_classification_head("rotten_tomatoes", num_labels=2)
# Activate the adapter
model.train_adapter("rotten_tomatoes")

It would be convenient for the users if the functionality to add adapter modules is included while building an AdaptiveModel in FARM. If the adapter modules are included in the model, all weights of the pre-trained model (for example, BERT) should be frozen, and only the adapter weights should be updated during training.

I am currently getting started with the adapter-transformers library and can surely share my results here once it's all done.
