### ISSUE TITLE
GPU usage very low in inferences

### ISSUE THREAD

**Issue by bipinkc19** [deepset-ai/FARM#752]
**Question**
Farm when use_gpu=True is using very low gpu.
How do I up this? 
\

**Comment by Timoeller** [comment]
Hey, this depends a lot on the data you put into the system. Can you give some more details on this data.

Also inference often does not fully leverage the GPU RAM, since communication between CPU and GPU is the bottleneck there.

In the meantime you can set `batch_size=40` and `num_processes=1`, this should improve GPU usage for most cases.

**Comment by Timoeller** [comment]
Issue seems resolved, closing now, feel free to reopen
