### ISSUE TITLE
Could not convert labels to ids via label_list

### ISSUE THREAD

**Issue by amoelle** [deepset-ai/FARM#99]
Hi there,

when i try to build a DataSilo with TextClassificationProcessor i get the following error:
"Could not convert labels to ids via label_list"

The label_list i give to the processor is fine however. I investigated a bit and the error seems to appear when 'label_raw = sample.clear_text[label_name]' is executed in the input_feautes.py
It looks like the clear_text dictionary does not have a key called "text_classification_label" even though that's the name of my label column.

`
        bert_df = pd.DataFrame({
            'text':self.df['Originalbeitrag'], 
            'text_classification_label':self.df['Tonalität des Artikels/Themas']
        }).dropna()
        print(bert_df.head())
        train_set = bert_df.sample(frac=0.8)
        test_set = bert_df.drop(train_set.index)
        print(train_set.head())
        train_set.to_csv('data/train.tsv', sep='\t', index=True, header=['text', 'text_classification_label'], columns=train_set.columns)
        test_set.to_csv('data/test.tsv',  sep='\t', index=True, header=['text', 'text_classification_label'], columns=test_set.columns)`
**Describe the bug**

**Error message**
Error that was thrown (if available)

**Expected behavior**

**Additional context**
Add any other context about the problem here, like type of downstream task, part of  etc.. 

**To Reproduce**
Steps to reproduce the behavior

**System:**
 - OS: 
 - GPU/CPU:
 - FARM version:

**Comment by Timoeller** [comment]
Resolved itself? : )

Anyways, your problem is a critical point. We are currently improving the error messages when dealing with custom input data. The code hidden in the parent Processor class can be sometimes confusing for people new to FARM. You can visually inspect your data processing when we log samples to the console. Or you go in debug mode and see how the data flows, especially along the functions defined [here](https://github.com/deepset-ai/FARM/blob/5c93e1e0a31306b987d7ec7ead87381784f2b251/farm/data_handler/processor.py#L311).

Normally this error comes from input data not in the right format, especially when dealing with comma separated files and a text column often containing the separator or newlines (or any other wierd string symbols).
So please hang in there and ask questions through our github issues page here.

**Comment by amoelle** [comment]
Hi, sorry accidentally pressed enter before i was done typing :D I have updated my comment from earlier.

Thanks for your support so far, will look into it tomorrow again!

**Comment by Timoeller** [comment]
Hey @amoelle 
Thanks for updating the issue. Could you try renaming the "Tonalität des Artikels/Themas" column to anything but "text_classification_label". This is our internal string value, that gets assigned to label_name. If that solves the issue, we will need to add a check for that very case.

Otherwise could you verify with `self.df['Tonalität des Artikels/Themas'].unique()` that really all values occuring in that column are covered by the label list?

Thanks, looking forward to your reply tomorrow.

**Comment by amoelle** [comment]
Renaming the label column seems to work, thank you! :)
